package aoopproje;

import java.util.Vector;
import javax.swing.JOptionPane;

public class DiğerKullaniciEkranlari extends javax.swing.JFrame {
    Menu m = new Menu();
    BenimEkran be = new BenimEkran();
    private User diğerkullanici;

    public User getDiğerkullanici() {
        return diğerkullanici;
    }

    public void setDiğerkullanici(User diğerkullanici) {
        this.diğerkullanici = diğerkullanici;
    }
    AramaEkrani aramaEkrani = new AramaEkrani();
    public DiğerKullaniciEkranlari() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arkadaşlari_liste = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        grupları_liste = new javax.swing.JList<>();
        kullanici_ismi = new javax.swing.JTextField();
        çalişma_durumu = new javax.swing.JTextField();
        ilişki_durumu = new javax.swing.JTextField();
        arkadaş_ekle = new javax.swing.JButton();
        menüye_dön = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kullanıcının Duvarı:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("İlişki Durumu:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Çalışma Durumu:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Arkadaşları");

        arkadaşlari_liste.setBackground(new java.awt.Color(204, 204, 255));
        arkadaşlari_liste.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(arkadaşlari_liste);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Katıldığı Gruplar");

        grupları_liste.setBackground(new java.awt.Color(204, 204, 255));
        grupları_liste.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(grupları_liste);

        kullanici_ismi.setEditable(false);
        kullanici_ismi.setBackground(new java.awt.Color(204, 204, 255));
        kullanici_ismi.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        kullanici_ismi.setForeground(new java.awt.Color(255, 255, 255));
        kullanici_ismi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanici_ismiActionPerformed(evt);
            }
        });

        çalişma_durumu.setEditable(false);
        çalişma_durumu.setBackground(new java.awt.Color(204, 204, 255));
        çalişma_durumu.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        çalişma_durumu.setForeground(new java.awt.Color(255, 255, 255));

        ilişki_durumu.setEditable(false);
        ilişki_durumu.setBackground(new java.awt.Color(204, 204, 255));
        ilişki_durumu.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ilişki_durumu.setForeground(new java.awt.Color(255, 255, 255));

        arkadaş_ekle.setBackground(new java.awt.Color(204, 204, 255));
        arkadaş_ekle.setForeground(new java.awt.Color(255, 255, 255));
        arkadaş_ekle.setText("Arkadaş Ekle");
        arkadaş_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arkadaş_ekleActionPerformed(evt);
            }
        });

        menüye_dön.setBackground(new java.awt.Color(204, 204, 255));
        menüye_dön.setForeground(new java.awt.Color(255, 255, 255));
        menüye_dön.setText("Menüye Dön");
        menüye_dön.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menüye_dönActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addComponent(çalişma_durumu)
                        .addComponent(ilişki_durumu))
                    .addComponent(menüye_dön))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kullanici_ismi, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(arkadaş_ekle)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(arkadaş_ekle)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanici_ismi))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menüye_dön)
                        .addGap(19, 19, 19)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ilişki_durumu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(çalişma_durumu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kullanici_ismiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanici_ismiActionPerformed
        
    }//GEN-LAST:event_kullanici_ismiActionPerformed

    private void arkadaş_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arkadaş_ekleActionPerformed
        Singleton.getInstance().getGiris_yapan_kullanici().arkadasEkle(diğerkullanici);
        diğerkullanici.arkadasEkle(Singleton.getInstance().getGiris_yapan_kullanici());
        displayUserProfile();
        be.displayMyProfile();
        JOptionPane.showMessageDialog(this, "Arkadaş eklendi");
    }//GEN-LAST:event_arkadaş_ekleActionPerformed

    private void menüye_dönActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menüye_dönActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        aramaEkrani.dispose();
        dispose();
    }//GEN-LAST:event_menüye_dönActionPerformed
    public  void displayUserProfile() {
        // Implement this method to navigate to the user's profile
        // For example, you might open a new JFrame or update a panel with the user's information
        
        kullanici_ismi.setText(diğerkullanici.getKullanici_adi());
        çalişma_durumu.setText(diğerkullanici.getIsDurumu());
        if(diğerkullanici.isEvlilik() == true){
            ilişki_durumu.setText("Evli");
        }
        else {
            ilişki_durumu.setText("Bekar");
        }
        arkadaşlari_liste.setListData((Vector<? extends String>) diğerkullanici.getArkadaslar());
        grupları_liste.setListData((Vector<? extends String>) diğerkullanici.getGruplar());
        setVisible(true);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiğerKullaniciEkranlari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiğerKullaniciEkranlari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiğerKullaniciEkranlari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiğerKullaniciEkranlari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiğerKullaniciEkranlari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arkadaş_ekle;
    public javax.swing.JList<String> arkadaşlari_liste;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JList<String> grupları_liste;
    public javax.swing.JTextField ilişki_durumu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField kullanici_ismi;
    private javax.swing.JButton menüye_dön;
    public javax.swing.JTextField çalişma_durumu;
    // End of variables declaration//GEN-END:variables
    }
      
