
package aoopproje;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author mustafayigitguzel
 */
public class KayitGiris extends javax.swing.JFrame {    
    private static final String USER_FILE = "users.txt";
    private DefaultListModel<String> friendsListModel;
    private DefaultListModel<String> groupsListModel;

    public static ArrayList<User> user_list = new ArrayList<User>();

    public static ArrayList<User> getUser_list() {
        return user_list;
    }

    public static void setUser_list(ArrayList<User> user_list) {
        KayitGiris.user_list = user_list;
    }
    
    User kullanıcı1 = new User("mustafa", "123", false,"Part-Time");
    User kullanıcı2 = new User("ahmet", "1234", true,null);
    User kullanıcı3 = new User("semih", "12345", false,"Full_Time");
    
    /**
     * Creates new form KayıtGiriş
     */
    public KayitGiris() {
        initComponents();
        loadUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kullanıcı_adı = new javax.swing.JTextField();
        parola_alanı = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kayıt_ol = new javax.swing.JButton();
        giriş_yap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        kullanıcı_adı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanıcı_adıActionPerformed(evt);
            }
        });

        parola_alanı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parola_alanıActionPerformed(evt);
            }
        });

        jLabel1.setText("Kullanıcı ismi:");

        jLabel2.setText("Parola:");

        kayıt_ol.setText("Kayıt Ol");
        kayıt_ol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayıt_olActionPerformed(evt);
            }
        });

        giriş_yap.setText("Giriş Yap");
        giriş_yap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giriş_yapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kullanıcı_adı)
                    .addComponent(parola_alanı, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addGap(144, 144, 144))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(kayıt_ol)
                .addGap(57, 57, 57)
                .addComponent(giriş_yap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kullanıcı_adı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parola_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kayıt_ol)
                    .addComponent(giriş_yap))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void saveUsers() {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(USER_FILE))) {
            for (User user : user_list) {
                writer.write(user.getKullanici_adi() + "," + user.getParola() + "\n");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    private void loadUsers() {
        try (BufferedReader reader = new BufferedReader(new FileReader(USER_FILE))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                user_list.add(new User(parts[0], parts[1], false, null));
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    private void parola_alanıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parola_alanıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parola_alanıActionPerformed

    private void kayıt_olActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayıt_olActionPerformed
        String isim = this.kullanıcı_adı.getText();
        String şifre = new String(parola_alanı.getText());
        if(!isim.isEmpty() || !şifre.isEmpty()){
            
            user_list.add(new User(isim,şifre, false,null));
            saveUsers();
            JOptionPane.showMessageDialog(this, "Kayıt oldunuz.");
        }
        else{
            JOptionPane.showMessageDialog(this, "İçerikleri boş bırakmayın!");
        }
        
    }//GEN-LAST:event_kayıt_olActionPerformed

    private void giriş_yapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giriş_yapActionPerformed
        user_list.add(kullanıcı1);
        user_list.add(kullanıcı2);        
        user_list.add(kullanıcı3);
        kullanıcı1.arkadasEkle(kullanıcı2);
        kullanıcı1.arkadasEkle(kullanıcı3);
        String kullanci_adi = kullanıcı_adı.getText();
        String parola = new String(parola_alanı.getText());
        if(user_list.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hiçbir kullanıcı bulunmamaktadır.");
            
        }
        else {
            for(User user: user_list) {
                if(user.getKullanici_adi().equals(kullanci_adi) && user.getParola().equals(parola)){
                    JOptionPane.showMessageDialog(this, "Hoşgeldiniz, " + kullanci_adi);
                    Singleton singleton = Singleton.getInstance();
                    singleton.setGiris_yapan_kullanici(user);
                    user_list.add(singleton.getGiris_yapan_kullanici());
                    Menu m =new Menu();
                    m.setVisible(true);
                    dispose();
                    return;
                }
            }
            
            JOptionPane.showMessageDialog(this, "Böyle bir kullanıcı yok, kayıt olunuz!");

        }
    }//GEN-LAST:event_giriş_yapActionPerformed

    private void kullanıcı_adıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanıcı_adıActionPerformed
        
    }//GEN-LAST:event_kullanıcı_adıActionPerformed
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayitGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayitGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayitGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayitGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new KayitGiris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton giriş_yap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kayıt_ol;
    public javax.swing.JTextField kullanıcı_adı;
    private javax.swing.JTextField parola_alanı;
    // End of variables declaration//GEN-END:variables
}
